# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=32)),
                ('contact', models.CharField(max_length=128)),
                ('contact_phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=128)),
                ('introduction', models.TextField()),
                ('category', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('image_list', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RechargeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('amount', models.FloatField()),
                ('account', models.CharField(max_length=128)),
                ('channel', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('image', models.CharField(max_length=255)),
                ('recommend', models.TextField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('number', models.CharField(max_length=32)),
                ('payment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('number', models.IntegerField()),
                ('rating', models.IntegerField(verbose_name='\u6700\u5927\u53c2\u4e0e\u4eba\u6570')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_time', models.DateTimeField(auto_created=True)),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('Email', models.CharField(max_length=128, null=True)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='winner',
            field=models.ManyToManyField(to='sku.User'),
        ),
        migrations.AddField(
            model_name='shoppingrecord',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='sku.SKU'),
        ),
        migrations.AddField(
            model_name='shoppingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='sku.User'),
        ),
        migrations.AddField(
            model_name='share',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.SKU'),
        ),
        migrations.AddField(
            model_name='share',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku.User'),
        ),
        migrations.AddField(
            model_name='rechargeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge', to='sku.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='sku.User'),
        ),
    ]
