# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0002_auto_20161221_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='good',
        ),
        migrations.AlterField(
            model_name='shoppingrecord',
            name='number',
            field=models.CharField(max_length=32, verbose_name='\u593a\u5b9d\u53f7'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='number',
            field=models.IntegerField(verbose_name='\u6d3b\u52a8\u671f\u53f7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='\u8d26\u53f7'),
        ),
    ]
