# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0003_auto_20170109_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.AddField(
            model_name='shoppingrecord',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u4ed8\u6b3e\u6536\u8d27\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='sku',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
