# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sku', '0005_auto_20170111_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingrecord',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
